# Generated by Django 2.2.5 on 2019-11-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordListGenerate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('change_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyList.Wordlist')),
            ],
        ),
        migrations.CreateModel(
            name='GenerateWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('Type', models.CharField(blank=True, max_length=4, null=True)),
                ('gloss', models.CharField(max_length=500)),
                ('similar_list', models.CharField(blank=True, max_length=500, null=True)),
                ('antonym_list', models.CharField(blank=True, max_length=100, null=True)),
                ('genlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyList.WordListGenerate')),
            ],
        ),
    ]
